version: 2
jobs:
  test:
    docker:
      - image: cardboardci/tflint
    steps:
      - checkout
      - run:
          name: Lint Terraform for cluster
          command: |
            tflint --version
            cd examples/stage/odc_eks/
            tflint --module main.tf 
          environment:
            WORKSPACE: datakube-dev
workflows:
  version: 2
  test:
    jobs:
      - test
