version: 2
jobs:
  test:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run:
          name: Lint Terraform for cluster
          command: |
            apt-get update
            apt-get install -y wget sudo
            wget https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh
            bash install_linux.sh
            tflint --version
            cd examples/stage/odc_eks/
            tflint --module main.tf 
          environment:
            WORKSPACE: datakube-dev
workflows:
  version: 2
  test:
    jobs:
      - test
