version: 2
jobs:
  test:
    docker:
      - image: wata727/tflint
    steps:
      - checkout
      - run:
          name: Lint Terraform for cluster
          command: |
            export TERRAFORM_VERSION=0.12.12
            export AWS_ACCESS_KEY_ID="anaccesskey"
            export AWS_SECRET_ACCESS_KEY="asecretkey"
            export AWS_DEFAULT_REGION="us-west-2"
            apk update
            apk add curl jq python bash ca-certificates git openssl unzip wget
            mkdir tmp
            cd tmp
            wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
            unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip -d /usr/bin
            cd ..
            tflint --version
            cd examples/stage/odc_eks/
            terraform init
            tflint --module main.tf
            cd ../../../
            cd examples/stage/odc_k8s
            terraform init
            tflint --module *.tf
          environment:
            WORKSPACE: datakube-dev
workflows:
  version: 2
  test:
    jobs:
      - test
