apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ows-monitor
  labels:
    prometheus: default-prometheus
spec:
  selector:
    matchLabels:
      release: ows
  endpoints:
  - port: "80"
