image:
  repository: fluent/fluentd-kubernetes-daemonset
  tag: v1.3-debian-cloudwatch
logGroupName: datakube
awsRegion: ap-southeast-2
rbac:
  create: true
extraVars:
  - "{ name: FLUENT_UID, value: '0' }"
resources:
  limits:
    cpu: 100m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 200Mi
awsRole: eks-fluentd
