# https://github.com/justinbarrick/fluxcloud
# Allows us to get notifications from Flux without subscription to WeaveWorks Cloud
---
kind: Service
apiVersion: v1
metadata:
  name: fluxcloud
spec:
  selector:
    name: fluxcloud
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3032
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fluxcloud
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: fluxcloud
    spec:
      containers:
      - name: fluxcloud
        image: justinbarrick/fluxcloud:v0.3.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3032
        env:
        - name: SLACK_URL
          value: "https://hooks.slack.com/services/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"
        - name: SLACK_CHANNEL
          value: "#ga-wms-updates"
        # Or configure multiple channels
        # (comma separated <channel>=<namespace>) string:
        #  value: "#kubernetes=*,#team=team"
        - name: GITHUB_URL
          value: "https://bitbucket.org/geoscienceaustralia/datakube-apps"
        - name: LISTEN_ADDRESS
          value: ":3032"
        - name: SLACK_USERNAME
          value: Flux Deployer
        - name: SLACK_ICON_EMOJI
          value: ":developers:"
        - name: COMMIT_TEMPLATE
          value: "{{ .VCSLink }}/commits/{{ .Commit }}"

