apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
  name: monitor-ingress
  namespace: monitoring
spec:
  rules:
  - host: monitor.mgmt.{{ .Values.domain }}
    http:
      paths:
      - backend:
          serviceName: kube-prometheus-grafana
          servicePort: 80
        path: /*
  - host: alert.mgmt.{{ .Values.domain }}
    http:
      paths:
      - backend:
          serviceName: kube-prometheus-alertmanager
          servicePort: 9093
        path: /*

# # Kube-system Namespace
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   annotations:
#     nginx.ingress.kubernetes.io/secure-backends: "true"
#   name: dashboard-ingress
#   namespace: kube-system
# spec:
#   rules:
#   - host: dashboard.mgmt.{{ .Values.domain }}
#     http:
#       paths:
#       - backend:
#           serviceName: kubernetes-dashboard
#           servicePort: 443
#         path: /
# ---
# # Monitoring Namespace
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   annotations:
#     nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
#     nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start"
#   name: monitor-ingress
#   namespace: monitoring
# spec:
#   rules:
#   - host: monitor.mgmt.{{ .Values.domain }}
#     http:
#       paths:
#       - backend:
#           serviceName: kube-prometheus-grafana
#           servicePort: 80
#         path: /
#   - host: alert.mgmt.{{ .Values.domain }}
#     http:
#       paths:
#       - backend:
#           serviceName: kube-prometheus-alertmanager
#           servicePort: 9093
#         path: /
# ---
# # Default Namespace
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   annotations:
#     nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
#     nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start"
#   name: ambassador-ingress
#   namespace: default
# spec:
#   rules:
#   - host: prometheus.mgmt.{{ .Values.domain }}
#     http:
#       paths:
#       - backend:
#           serviceName: prometheus
#           servicePort: 9090
#         path: /
# ---
# # Oauth Proxy
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: oauth2-proxy
#   namespace: kube-system
#   annotations:
#     kubernetes.io/tls-acme: "true"
# spec:
#   rules:
#   - host: dashboard.mgmt.{{ .Values.domain }}
#     http:
#       paths:
#       - backend:
#           serviceName: oauth2-proxy
#           servicePort: 4180
#         path: /oauth2
#   - host: monitor.mgmt.{{ .Values.domain }}
#     http:
#       paths:
#       - backend:
#           serviceName: oauth2-proxy
#           servicePort: 4180
#         path: /oauth2
#   - host: alert.mgmt.{{ .Values.domain }}
#     http:
#       paths:
#       - backend:
#           serviceName: oauth2-proxy
#           servicePort: 4180
#         path: /oauth2
#   - host: ambassador.mgmt.{{ .Values.domain }}
#     http:
#       paths:
#       - backend:
#           serviceName: oauth2-proxy
#           servicePort: 4180
#         path: /oauth2
#   - host: prometheus.mgmt.{{ .Values.domain }}
#     http:
#       paths:
#       - backend:
#           serviceName: oauth2-proxy
#           servicePort: 4180
#         path: /oauth2
#   tls:
#   - secretName: oauth-mgmt-tls
#     hosts:
#     - dashboard.mgmt.{{ .Values.domain }}
#     - monitor.mgmt.{{ .Values.domain }}
#     - alert.mgmt.{{ .Values.domain }}
#     - prometheus.mgmt.{{ .Values.domain }}