apiVersion: v1
kind: Secret
metadata:
  name: azure
  namespace: kube-system
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
  clientId: {{ .Values.azure.clientID | b64enc | quote }}
  clientSecret: {{ .Values.azure.clientSecret | b64enc | quote }}
  proxySecret: {{ randAlphaNum 16 | b64enc | quote }}