apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-app: dashboard
  name: dashboard
  namespace: default
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: dashboard-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: dashboard
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""